server:
  port: ${PORT:8181}
  address: 0.0.0.0

spring:
  data:
    mongodb:
      uri: mongodb+srv://Node:node@node.lbg68pb.mongodb.net/?retryWrites=true&w=majority&authSource=admin&ssl=true&sslInvalidHostNameAllowed=true
      database: node
